application:
  subdomain: redink
  background_task: true
  public_path:
    - /
  routes:
    - /=http://redink:12398/
services:
  redink:
    # histonemax/redink:latest
    image: registry.lazycat.cloud/czyt/histonemax/redink:44d2bdff47147976
    binds:
      - /lzcapp/var/output:/app/output
      - /lzcapp/var/history:/app/history
      - /lzcapp/var/config:/app/config
    setup_script: |
      if [ ! -f /lzcapp/var/config/text_providers.yaml ]; then
         cp -r /app/text_providers.yaml /lzcapp/var/config/text_providers.yaml
      fi
      rm /app/text_providers.yaml
      ln -s /lzcapp/var/config/text_providers.yaml /app/text_providers.yaml

      if [ ! -f /lzcapp/var/config/image_providers.yaml ]; then
         cp -r /app/image_providers.yaml /lzcapp/var/config/image_providers.yaml
      fi
      rm /app/image_providers.yaml
      ln -s /lzcapp/var/config/image_providers.yaml /app/image_providers.yaml
